/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.panel.dashboard;

/**
 *
 * @author haris
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        totalPendapatanCard = new javax.swing.JPanel();
        totalPendapatanLabel = new javax.swing.JLabel();
        totalPendapatanValue = new javax.swing.JLabel();
        totalTransaksiCard = new javax.swing.JPanel();
        totalTransaksiLabel = new javax.swing.JLabel();
        totalTransaksiValue = new javax.swing.JLabel();
        stokKritisCard = new javax.swing.JPanel();
        stokKritisLabel = new javax.swing.JLabel();
        stokKritisValue = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTerakhirTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setForeground(new java.awt.Color(0, 0, 0));
        rootPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        rootPanel.setPreferredSize(new java.awt.Dimension(868, 479));

        title.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Dashboard");

        totalPendapatanCard.setBackground(new java.awt.Color(0, 49, 31));

        totalPendapatanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalPendapatanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPendapatanLabel.setText("Total Pendapatan");

        totalPendapatanValue.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        totalPendapatanValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPendapatanValue.setText("Rp0,00");

        javax.swing.GroupLayout totalPendapatanCardLayout = new javax.swing.GroupLayout(totalPendapatanCard);
        totalPendapatanCard.setLayout(totalPendapatanCardLayout);
        totalPendapatanCardLayout.setHorizontalGroup(
            totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(totalPendapatanValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalPendapatanCardLayout.setVerticalGroup(
            totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalPendapatanLabel)
                .addGap(18, 18, 18)
                .addComponent(totalPendapatanValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        totalTransaksiCard.setBackground(new java.awt.Color(0, 49, 31));

        totalTransaksiLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalTransaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTransaksiLabel.setText("Total Transaksi");

        totalTransaksiValue.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        totalTransaksiValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTransaksiValue.setText("Rp0,00");

        javax.swing.GroupLayout totalTransaksiCardLayout = new javax.swing.GroupLayout(totalTransaksiCard);
        totalTransaksiCard.setLayout(totalTransaksiCardLayout);
        totalTransaksiCardLayout.setHorizontalGroup(
            totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTransaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(totalTransaksiValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalTransaksiCardLayout.setVerticalGroup(
            totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTransaksiLabel)
                .addGap(18, 18, 18)
                .addComponent(totalTransaksiValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        stokKritisCard.setBackground(new java.awt.Color(0, 49, 31));

        stokKritisLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        stokKritisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stokKritisLabel.setText("Stok Kritis");

        stokKritisValue.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        stokKritisValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stokKritisValue.setText("Rp0,00");

        javax.swing.GroupLayout stokKritisCardLayout = new javax.swing.GroupLayout(stokKritisCard);
        stokKritisCard.setLayout(stokKritisCardLayout);
        stokKritisCardLayout.setHorizontalGroup(
            stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokKritisCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stokKritisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(stokKritisValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        stokKritisCardLayout.setVerticalGroup(
            stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokKritisCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stokKritisLabel)
                .addGap(18, 18, 18)
                .addComponent(stokKritisValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tableLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 20)); // NOI18N
        tableLabel.setForeground(new java.awt.Color(0, 0, 0));
        tableLabel.setText("Transaksi Terbaru");

        transaksiTerakhirTable.setBackground(new java.awt.Color(255, 255, 255));
        transaksiTerakhirTable.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        transaksiTerakhirTable.setForeground(new java.awt.Color(0, 0, 0));
        transaksiTerakhirTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nomor Polisi", "Keluhan", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transaksiTerakhirTable);
        if (transaksiTerakhirTable.getColumnModel().getColumnCount() > 0) {
            transaksiTerakhirTable.getColumnModel().getColumn(0).setResizable(false);
            transaksiTerakhirTable.getColumnModel().getColumn(1).setResizable(false);
            transaksiTerakhirTable.getColumnModel().getColumn(2).setResizable(false);
            transaksiTerakhirTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(totalPendapatanCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(totalTransaksiCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(stokKritisCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTransaksiCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokKritisCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(tableLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel stokKritisCard;
    private javax.swing.JLabel stokKritisLabel;
    private javax.swing.JLabel stokKritisValue;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel totalPendapatanCard;
    private javax.swing.JLabel totalPendapatanLabel;
    private javax.swing.JLabel totalPendapatanValue;
    private javax.swing.JPanel totalTransaksiCard;
    private javax.swing.JLabel totalTransaksiLabel;
    private javax.swing.JLabel totalTransaksiValue;
    private javax.swing.JTable transaksiTerakhirTable;
    // End of variables declaration//GEN-END:variables
}
