/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.dashboard;

import dto.response.DashboardResponseDTO;
import dto.response.TransaksiResponseDTO;
import service.DashboardService;
import util.Response;

import java.util.List;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haris
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        initialLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        totalPendapatanCard = new javax.swing.JPanel();
        totalPendapatanLabel = new javax.swing.JLabel();
        totalPendapatanValue = new javax.swing.JLabel();
        totalTransaksiCard = new javax.swing.JPanel();
        totalTransaksiLabel = new javax.swing.JLabel();
        totalTransaksiValue = new javax.swing.JLabel();
        stokKritisCard = new javax.swing.JPanel();
        stokKritisLabel = new javax.swing.JLabel();
        stokKritisValue = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaksiTerakhirTable = new javax.swing.JTable();

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        rootPanel.setPreferredSize(new java.awt.Dimension(868, 479));

        title.setFont(new java.awt.Font("Microsoft JhengHei", 1, 20)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Dashboard");

        totalPendapatanCard.setBackground(new java.awt.Color(0, 49, 31));

        totalPendapatanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalPendapatanLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPendapatanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPendapatanLabel.setText("Pendapatan Hari ini");

        totalPendapatanValue.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalPendapatanValue.setForeground(new java.awt.Color(255, 255, 255));
        totalPendapatanValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPendapatanValue.setText("Rp0,00");

        javax.swing.GroupLayout totalPendapatanCardLayout = new javax.swing.GroupLayout(totalPendapatanCard);
        totalPendapatanCard.setLayout(totalPendapatanCardLayout);
        totalPendapatanCardLayout.setHorizontalGroup(
            totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(totalPendapatanValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalPendapatanCardLayout.setVerticalGroup(
            totalPendapatanCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPendapatanCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(totalPendapatanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalPendapatanValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        totalTransaksiCard.setBackground(new java.awt.Color(0, 49, 31));

        totalTransaksiLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalTransaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalTransaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTransaksiLabel.setText("Transaksi Hari Ini");

        totalTransaksiValue.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        totalTransaksiValue.setForeground(new java.awt.Color(255, 255, 255));
        totalTransaksiValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTransaksiValue.setText("0");

        javax.swing.GroupLayout totalTransaksiCardLayout = new javax.swing.GroupLayout(totalTransaksiCard);
        totalTransaksiCard.setLayout(totalTransaksiCardLayout);
        totalTransaksiCardLayout.setHorizontalGroup(
            totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTransaksiValue, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(totalTransaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        totalTransaksiCardLayout.setVerticalGroup(
            totalTransaksiCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTransaksiCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(totalTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalTransaksiValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        stokKritisCard.setBackground(new java.awt.Color(0, 49, 31));

        stokKritisLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        stokKritisLabel.setForeground(new java.awt.Color(255, 255, 255));
        stokKritisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stokKritisLabel.setText("Stok Kritis");

        stokKritisValue.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        stokKritisValue.setForeground(new java.awt.Color(255, 255, 255));
        stokKritisValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stokKritisValue.setText("0");

        javax.swing.GroupLayout stokKritisCardLayout = new javax.swing.GroupLayout(stokKritisCard);
        stokKritisCard.setLayout(stokKritisCardLayout);
        stokKritisCardLayout.setHorizontalGroup(
            stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokKritisCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stokKritisValue, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(stokKritisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        stokKritisCardLayout.setVerticalGroup(
            stokKritisCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokKritisCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(stokKritisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stokKritisValue)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tableLabel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 20)); // NOI18N
        tableLabel.setForeground(new java.awt.Color(0, 0, 0));
        tableLabel.setText("Transaksi Terbaru");

        transaksiTerakhirTable.setBackground(new java.awt.Color(255, 255, 255));
        transaksiTerakhirTable.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        transaksiTerakhirTable.setForeground(new java.awt.Color(0, 0, 0));
        transaksiTerakhirTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal Transaksi", "Nomor Polisi", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transaksiTerakhirTable);

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(totalPendapatanCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(totalTransaksiCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(stokKritisCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPendapatanCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTransaksiCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokKritisCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(tableLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initialLoad() {
        DashboardService service = new DashboardService();
        Response<DashboardResponseDTO> response = service.getDashboardData();
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DashboardResponseDTO data = response.getData();
        totalPendapatanValue.setText(String.format("Rp%,.2f", data.getTotalPendapatan()));
        totalTransaksiValue.setText(String.valueOf(data.getTotalTransaksi()));
        stokKritisValue.setText(String.valueOf(data.getBarangStokRendah()));

        List<TransaksiResponseDTO> transaksiList = data.getTransaksiTerakhir();

        DefaultTableModel model = (DefaultTableModel) transaksiTerakhirTable.getModel();
        model.setRowCount(0);
        for (TransaksiResponseDTO transaksi : transaksiList) {
            Object[] row = new Object[]{
                transaksi.getTanggalFormatted(),
                transaksi.getNopol(),
                String.format("Rp%,.2f", transaksi.getTotalBelanja())
            };
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel stokKritisCard;
    private javax.swing.JLabel stokKritisLabel;
    private javax.swing.JLabel stokKritisValue;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel totalPendapatanCard;
    private javax.swing.JLabel totalPendapatanLabel;
    private javax.swing.JLabel totalPendapatanValue;
    private javax.swing.JPanel totalTransaksiCard;
    private javax.swing.JLabel totalTransaksiLabel;
    private javax.swing.JLabel totalTransaksiValue;
    private javax.swing.JTable transaksiTerakhirTable;
    // End of variables declaration//GEN-END:variables
}
