/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author haris
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        navigationPanel = new javax.swing.JPanel();
        dashboardNav = new javax.swing.JButton();
        stokBarangNav = new javax.swing.JButton();
        mekanikNav = new javax.swing.JButton();
        pelangganNav = new javax.swing.JButton();
        transaksiNav = new javax.swing.JButton();
        laporanNav = new javax.swing.JButton();
        logoutNav = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(0, 49, 31));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        navigationPanel.setBackground(new java.awt.Color(0, 49, 31));

        dashboardNav.setBackground(new java.awt.Color(254, 250, 224));
        dashboardNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        dashboardNav.setForeground(new java.awt.Color(0, 49, 31));
        dashboardNav.setText("Dashboard");

        stokBarangNav.setBackground(new java.awt.Color(254, 250, 224));
        stokBarangNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        stokBarangNav.setForeground(new java.awt.Color(0, 49, 31));
        stokBarangNav.setText("Stok Barang");

        mekanikNav.setBackground(new java.awt.Color(254, 250, 224));
        mekanikNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        mekanikNav.setForeground(new java.awt.Color(0, 49, 31));
        mekanikNav.setText("Mekanik");

        pelangganNav.setBackground(new java.awt.Color(254, 250, 224));
        pelangganNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        pelangganNav.setForeground(new java.awt.Color(0, 49, 31));
        pelangganNav.setText("Pelanggan");

        transaksiNav.setBackground(new java.awt.Color(254, 250, 224));
        transaksiNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        transaksiNav.setForeground(new java.awt.Color(0, 49, 31));
        transaksiNav.setText("Transaksi");

        laporanNav.setBackground(new java.awt.Color(254, 250, 224));
        laporanNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        laporanNav.setForeground(new java.awt.Color(0, 49, 31));
        laporanNav.setText("Laporan");

        logoutNav.setBackground(new java.awt.Color(254, 250, 224));
        logoutNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        logoutNav.setForeground(new java.awt.Color(0, 49, 31));
        logoutNav.setText("Keluar");

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stokBarangNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(mekanikNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(pelangganNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(transaksiNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(laporanNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(logoutNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dashboardNav)
                .addGap(19, 19, 19)
                .addComponent(stokBarangNav)
                .addGap(19, 19, 19)
                .addComponent(mekanikNav)
                .addGap(19, 19, 19)
                .addComponent(pelangganNav)
                .addGap(19, 19, 19)
                .addComponent(transaksiNav)
                .addGap(19, 19, 19)
                .addComponent(laporanNav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutNav)
                .addGap(14, 14, 14))
        );

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardNav;
    private javax.swing.JButton laporanNav;
    private javax.swing.JButton logoutNav;
    private javax.swing.JButton mekanikNav;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton pelangganNav;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton stokBarangNav;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton transaksiNav;
    // End of variables declaration//GEN-END:variables
}
