/*
Nama            : (08) Raissa Christabel Sebayang
                  (44) Abraham Gomes Samosir
                  (74) Haris Herdiansyah
*/

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.ApplicationState;
import util.Routing;
import view.panel.akun.AkunPanel;
import view.panel.barang.BarangPanel;
import view.panel.dashboard.DashboardPanel;
import view.panel.mekanik.MekanikPanel;
import view.panel.pelanggan.PelangganPanel;
import view.panel.transaksi.HistoriTransaksiPanel;
import view.panel.transaksi.TransaksiPanel;

import java.awt.*;

/**
 *
 * @author haris
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        ApplicationState appState = ApplicationState.getInstance();

        if (appState.getAdmin() == null) {
            logger.severe("Admin is not authenticated, redirecting to LoginFrame");
            new LoginFrame().setVisible(true);
            dispose();
            return;
        }

        initComponents();

        contentPanel.add(new DashboardPanel(), Routing.DASHBOARD.toString());
        contentPanel.add(new AkunPanel(), Routing.AKUN.toString());
        contentPanel.add(new BarangPanel(), Routing.BARANG.toString());
        contentPanel.add(new MekanikPanel(), Routing.MEKANIK.toString());
        contentPanel.add(new PelangganPanel(), Routing.PELANGGAN.toString());
        contentPanel.add(new TransaksiPanel(), Routing.TRANSAKSI.toString());
        contentPanel.add(new HistoriTransaksiPanel(), Routing.HISTORI_TRANSAKSI.toString());

        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.DASHBOARD.toString());

        appState.setContentPanel(contentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navigationPanel = new javax.swing.JPanel();
        stokBarangNav = new javax.swing.JButton();
        mekanikNav = new javax.swing.JButton();
        pelangganNav = new javax.swing.JButton();
        transaksiNav = new javax.swing.JButton();
        laporanNav = new javax.swing.JButton();
        logoutNav = new javax.swing.JButton();
        dashboardNav = new javax.swing.JButton();
        akunNav = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(0, 49, 31));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KELOLA BENGKEL");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        navigationPanel.setBackground(new java.awt.Color(0, 49, 31));

        stokBarangNav.setBackground(new java.awt.Color(254, 250, 224));
        stokBarangNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        stokBarangNav.setForeground(new java.awt.Color(0, 49, 31));
        stokBarangNav.setText("Barang");
        stokBarangNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokBarangNavActionPerformed(evt);
            }
        });

        mekanikNav.setBackground(new java.awt.Color(254, 250, 224));
        mekanikNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        mekanikNav.setForeground(new java.awt.Color(0, 49, 31));
        mekanikNav.setText("Mekanik");
        mekanikNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mekanikNavActionPerformed(evt);
            }
        });

        pelangganNav.setBackground(new java.awt.Color(254, 250, 224));
        pelangganNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        pelangganNav.setForeground(new java.awt.Color(0, 49, 31));
        pelangganNav.setText("Pelanggan");
        pelangganNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganNavActionPerformed(evt);
            }
        });

        transaksiNav.setBackground(new java.awt.Color(254, 250, 224));
        transaksiNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        transaksiNav.setForeground(new java.awt.Color(0, 49, 31));
        transaksiNav.setText("Transaksi");
        transaksiNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiNavActionPerformed(evt);
            }
        });

        laporanNav.setBackground(new java.awt.Color(254, 250, 224));
        laporanNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        laporanNav.setForeground(new java.awt.Color(0, 49, 31));
        laporanNav.setText("Riwayat");
        laporanNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanNavActionPerformed(evt);
            }
        });

        logoutNav.setBackground(new java.awt.Color(220, 53, 69));
        logoutNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        logoutNav.setForeground(new java.awt.Color(255, 255, 255));
        logoutNav.setText("Keluar");
        logoutNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutNavActionPerformed(evt);
            }
        });

        dashboardNav.setBackground(new java.awt.Color(254, 250, 224));
        dashboardNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        dashboardNav.setForeground(new java.awt.Color(0, 49, 31));
        dashboardNav.setText("Dashboard");
        dashboardNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardNavActionPerformed(evt);
            }
        });

        akunNav.setBackground(new java.awt.Color(254, 250, 224));
        akunNav.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        akunNav.setForeground(new java.awt.Color(0, 49, 31));
        akunNav.setText("Akun");
        akunNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunNavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stokBarangNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(mekanikNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(pelangganNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(transaksiNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(laporanNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(logoutNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(akunNav, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(dashboardNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardNav)
                .addGap(18, 18, 18)
                .addComponent(akunNav)
                .addGap(18, 18, 18)
                .addComponent(stokBarangNav)
                .addGap(18, 18, 18)
                .addComponent(mekanikNav)
                .addGap(18, 18, 18)
                .addComponent(pelangganNav)
                .addGap(18, 18, 18)
                .addComponent(transaksiNav)
                .addGap(18, 18, 18)
                .addComponent(laporanNav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(logoutNav)
                .addGap(14, 14, 14))
        );

        contentPanel.setBackground(new java.awt.Color(223, 226, 220));
        contentPanel.setOpaque(false);
        contentPanel.setPreferredSize(new java.awt.Dimension(868, 479));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.DASHBOARD.toString());
    }//GEN-LAST:event_dashboardNavActionPerformed

    private void stokBarangNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokBarangNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.BARANG.toString());
    }//GEN-LAST:event_stokBarangNavActionPerformed

    private void mekanikNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mekanikNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.MEKANIK.toString());
    }//GEN-LAST:event_mekanikNavActionPerformed

    private void pelangganNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.PELANGGAN.toString());
    }//GEN-LAST:event_pelangganNavActionPerformed

    private void transaksiNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.TRANSAKSI.toString());
    }//GEN-LAST:event_transaksiNavActionPerformed

    private void laporanNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.HISTORI_TRANSAKSI.toString());
    }//GEN-LAST:event_laporanNavActionPerformed

    private void logoutNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutNavActionPerformed
        // TODO add your handling code here:
        ApplicationState appState = ApplicationState.getInstance();
        appState.setAdmin(null);
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutNavActionPerformed

    private void akunNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunNavActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (contentPanel.getLayout());
        cl.show(contentPanel, Routing.AKUN.toString());
    }//GEN-LAST:event_akunNavActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunNav;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardNav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporanNav;
    private javax.swing.JButton logoutNav;
    private javax.swing.JButton mekanikNav;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton pelangganNav;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton stokBarangNav;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton transaksiNav;
    // End of variables declaration//GEN-END:variables
}
