/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.barang;

/**
 *
 * @author haris
 */
public class FormBarangPanel extends javax.swing.JPanel {
    private boolean isEdit = false;
    
    /**
     * Creates new form FormBarangPanel
     */
    public FormBarangPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Batal = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        namaBarangLabel = new javax.swing.JLabel();
        namaBarangField = new javax.swing.JTextField();
        stokBarangLabel = new javax.swing.JLabel();
        stokBarangField = new javax.swing.JTextField();
        hargaBeliLabel = new javax.swing.JLabel();
        hargaBeliField = new javax.swing.JTextField();
        hargaJualLabel = new javax.swing.JLabel();
        hargaJualField = new javax.swing.JTextField();

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setForeground(new java.awt.Color(0, 0, 0));
        rootPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        rootPanel.setPreferredSize(new java.awt.Dimension(868, 479));

        title.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText(this.isEdit ? "Edit Barang" : "Tambah Barang");

        Batal.setBackground(new java.awt.Color(108, 117, 125));
        Batal.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Batal.setForeground(new java.awt.Color(255, 255, 255));
        Batal.setText("Batal");

        addBtn.setBackground(new java.awt.Color(13, 110, 253));
        addBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText(this.isEdit ? "Edit" : "Tambah");

        namaBarangLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        namaBarangLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaBarangLabel.setText("Nama Barang");

        namaBarangField.setBackground(new java.awt.Color(255, 255, 255));
        namaBarangField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        namaBarangField.setForeground(new java.awt.Color(0, 0, 0));

        stokBarangLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        stokBarangLabel.setForeground(new java.awt.Color(0, 0, 0));
        stokBarangLabel.setText("Stok Barang");

        stokBarangField.setBackground(new java.awt.Color(255, 255, 255));
        stokBarangField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        stokBarangField.setForeground(new java.awt.Color(0, 0, 0));

        hargaBeliLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaBeliLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaBeliLabel.setText("Harga Beli (Modal)");

        hargaBeliField.setBackground(new java.awt.Color(255, 255, 255));
        hargaBeliField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaBeliField.setForeground(new java.awt.Color(0, 0, 0));

        hargaJualLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaJualLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaJualLabel.setText("Harga Jual");

        hargaJualField.setBackground(new java.awt.Color(255, 255, 255));
        hargaJualField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaJualField.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(488, 488, 488)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaBarangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaBeliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stokBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stokBarangLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaJualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaJualField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(37, 37, 37)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBarangLabel)
                    .addComponent(stokBarangLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaBeliLabel)
                    .addComponent(hargaJualLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaJualField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Batal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField hargaBeliField;
    private javax.swing.JLabel hargaBeliLabel;
    private javax.swing.JTextField hargaJualField;
    private javax.swing.JLabel hargaJualLabel;
    private javax.swing.JTextField namaBarangField;
    private javax.swing.JLabel namaBarangLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTextField stokBarangField;
    private javax.swing.JLabel stokBarangLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
