/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.transaksi;

import view.component.ComboBoxItem;

/**
 *
 * @author haris
 */
public class TransaksiPanel extends javax.swing.JPanel {

    /**
     * Creates new form TransaksiPanel
     */
    public TransaksiPanel() {
        initComponents();

        pelangganField.setEnabled(false);
        mekanikComboBox.setEnabled(false);
        keluhanField.setEnabled(false);

        String jenis = (String) jenisComboBox.getSelectedItem();
        if (jenis != null && jenis.equals("JASA")) {
            namaBarangComboBox.setEnabled(false);
            jumlahItemField.setEnabled(false);
            jumlahItemField.setText(String.valueOf(1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nopolLabel = new javax.swing.JLabel();
        nopolField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        pelangganLabel = new javax.swing.JLabel();
        pelangganField = new javax.swing.JTextField();
        mekanikLabel = new javax.swing.JLabel();
        mekanikComboBox = new javax.swing.JComboBox<>();
        keluhanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluhanField = new javax.swing.JTextArea();
        separator = new javax.swing.JSeparator();
        jenisLabel = new javax.swing.JLabel();
        jenisComboBox = new javax.swing.JComboBox<>();
        namaBarangLabel = new javax.swing.JLabel();
        namaBarangComboBox = new javax.swing.JComboBox<>();
        jumlahItemLabel = new javax.swing.JLabel();
        jumlahItemField = new javax.swing.JTextField();
        hargaDibayarLabel = new javax.swing.JLabel();
        hargaDibayarField = new javax.swing.JTextField();
        catatanLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatanField = new javax.swing.JTextArea();
        listBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setForeground(new java.awt.Color(0, 0, 0));
        rootPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        rootPanel.setPreferredSize(new java.awt.Dimension(868, 479));

        title.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Transaksi");

        nopolLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        nopolLabel.setForeground(new java.awt.Color(0, 0, 0));
        nopolLabel.setText("No. Polisi Kendaraan");

        nopolField.setBackground(new java.awt.Color(255, 255, 255));
        nopolField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        nopolField.setForeground(new java.awt.Color(0, 0, 0));

        searchBtn.setBackground(new java.awt.Color(108, 117, 125));
        searchBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");

        pelangganLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        pelangganLabel.setForeground(new java.awt.Color(0, 0, 0));
        pelangganLabel.setText("Nama Pelanggan");

        pelangganField.setBackground(new java.awt.Color(255, 255, 255));
        pelangganField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        pelangganField.setForeground(new java.awt.Color(0, 0, 0));

        mekanikLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        mekanikLabel.setForeground(new java.awt.Color(0, 0, 0));
        mekanikLabel.setText("Mekanik");

        mekanikComboBox.setBackground(new java.awt.Color(255, 255, 255));
        mekanikComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        mekanikComboBox.setForeground(new java.awt.Color(0, 0, 0));

        keluhanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        keluhanLabel.setForeground(new java.awt.Color(0, 0, 0));
        keluhanLabel.setText("Keluhan");

        keluhanField.setBackground(new java.awt.Color(255, 255, 255));
        keluhanField.setColumns(20);
        keluhanField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        keluhanField.setForeground(new java.awt.Color(0, 0, 0));
        keluhanField.setRows(5);
        jScrollPane1.setViewportView(keluhanField);

        jenisLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jenisLabel.setForeground(new java.awt.Color(0, 0, 0));
        jenisLabel.setText("Jenis");

        jenisComboBox.setBackground(new java.awt.Color(255, 255, 255));
        jenisComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jenisComboBox.setForeground(new java.awt.Color(0, 0, 0));
        jenisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JASA", "BARANG" }));

        namaBarangLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        namaBarangLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaBarangLabel.setText("Nama Barang");

        namaBarangComboBox.setBackground(new java.awt.Color(255, 255, 255));
        namaBarangComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        namaBarangComboBox.setForeground(new java.awt.Color(0, 0, 0));

        jumlahItemLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jumlahItemLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahItemLabel.setText("Jumlah");

        jumlahItemField.setBackground(new java.awt.Color(255, 255, 255));
        jumlahItemField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jumlahItemField.setForeground(new java.awt.Color(0, 0, 0));

        hargaDibayarLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaDibayarLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaDibayarLabel.setText("Harga Dibayar");

        hargaDibayarField.setBackground(new java.awt.Color(255, 255, 255));
        hargaDibayarField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaDibayarField.setForeground(new java.awt.Color(0, 0, 0));

        catatanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        catatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        catatanLabel.setText("Catatan");

        catatanField.setBackground(new java.awt.Color(255, 255, 255));
        catatanField.setColumns(20);
        catatanField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        catatanField.setForeground(new java.awt.Color(0, 0, 0));
        catatanField.setRows(5);
        jScrollPane2.setViewportView(catatanField);

        listBtn.setBackground(new java.awt.Color(108, 117, 125));
        listBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        listBtn.setForeground(new java.awt.Color(255, 255, 255));
        listBtn.setText("Lihat Detail");

        addBtn.setBackground(new java.awt.Color(13, 110, 253));
        addBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah Item");

        saveBtn.setBackground(new java.awt.Color(25, 135, 84));
        saveBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keluhanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mekanikLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pelangganLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nopolLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn))
                            .addComponent(mekanikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(pelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(394, 394, 394))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(separator)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaBarangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahItemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(catatanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))))))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nopolLabel)
                    .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelangganLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mekanikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mekanikLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluhanLabel))
                .addGap(19, 19, 19)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaBarangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarangLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahItemField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahItemLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaDibayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarLabel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea catatanField;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextField hargaDibayarField;
    private javax.swing.JLabel hargaDibayarLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisComboBox;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField jumlahItemField;
    private javax.swing.JLabel jumlahItemLabel;
    private javax.swing.JTextArea keluhanField;
    private javax.swing.JLabel keluhanLabel;
    private javax.swing.JButton listBtn;
    private javax.swing.JComboBox<ComboBoxItem> mekanikComboBox;
    private javax.swing.JLabel mekanikLabel;
    private javax.swing.JComboBox<ComboBoxItem> namaBarangComboBox;
    private javax.swing.JLabel namaBarangLabel;
    private javax.swing.JTextField nopolField;
    private javax.swing.JLabel nopolLabel;
    private javax.swing.JTextField pelangganField;
    private javax.swing.JLabel pelangganLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
