/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel.transaksi;

import dto.request.TransaksiDetailRequestDTO;
import dto.request.TransaksiRequestDTO;
import dto.response.BarangResponseDTO;
import dto.response.MekanikResponseDTO;
import dto.response.PelangganResponseDTO;
import service.BarangService;
import service.MekanikService;
import service.PelangganService;
import service.TransaksiService;
import util.Response;
import view.component.ComboBoxItem;
import view.component.DetailTransaksiDialog;

import javax.swing.*;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author haris
 */
public class TransaksiPanel extends javax.swing.JPanel {
    private PelangganService pelangganService = new PelangganService();
    private BarangService barangService = new BarangService();
    private MekanikService mekanikService = new MekanikService();
    private TransaksiService transaksiService = new TransaksiService();
    private TransaksiRequestDTO requestDTO = new TransaksiRequestDTO();
    private List<BarangResponseDTO> barangList = null;

    /**
     * Creates new form TransaksiPanel
     */
    public TransaksiPanel() {
        initComponents();

        pelangganField.setEnabled(false);
        mekanikComboBox.setEnabled(false);
        keluhanField.setEnabled(false);

        resetAfterAdd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nopolLabel = new javax.swing.JLabel();
        nopolField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        pelangganLabel = new javax.swing.JLabel();
        pelangganField = new javax.swing.JTextField();
        mekanikLabel = new javax.swing.JLabel();
        mekanikComboBox = new javax.swing.JComboBox<>();
        keluhanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluhanField = new javax.swing.JTextArea();
        separator = new javax.swing.JSeparator();
        jenisLabel = new javax.swing.JLabel();
        jenisComboBox = new javax.swing.JComboBox<>();
        namaBarangLabel = new javax.swing.JLabel();
        namaBarangComboBox = new javax.swing.JComboBox<>();
        jumlahItemLabel = new javax.swing.JLabel();
        jumlahItemField = new javax.swing.JTextField();
        hargaDibayarLabel = new javax.swing.JLabel();
        hargaDibayarField = new javax.swing.JTextField();
        catatanLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatanField = new javax.swing.JTextArea();
        listBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        rootPanel.setPreferredSize(new java.awt.Dimension(868, 479));

        title.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Transaksi");

        nopolLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        nopolLabel.setForeground(new java.awt.Color(0, 0, 0));
        nopolLabel.setText("No. Polisi Kendaraan");

        nopolField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        searchBtn.setBackground(new java.awt.Color(108, 117, 125));
        searchBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        pelangganLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        pelangganLabel.setForeground(new java.awt.Color(0, 0, 0));
        pelangganLabel.setText("Nama Pelanggan");

        pelangganField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        mekanikLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        mekanikLabel.setForeground(new java.awt.Color(0, 0, 0));
        mekanikLabel.setText("Mekanik");

        mekanikComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        keluhanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        keluhanLabel.setForeground(new java.awt.Color(0, 0, 0));
        keluhanLabel.setText("Keluhan");

        keluhanField.setColumns(20);
        keluhanField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        keluhanField.setRows(5);
        jScrollPane1.setViewportView(keluhanField);

        jenisLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jenisLabel.setForeground(new java.awt.Color(0, 0, 0));
        jenisLabel.setText("Jenis");

        jenisComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jenisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JASA", "BARANG" }));
        jenisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisComboBoxActionPerformed(evt);
            }
        });

        namaBarangLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        namaBarangLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaBarangLabel.setText("Nama Barang");

        namaBarangComboBox.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        jumlahItemLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jumlahItemLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahItemLabel.setText("Jumlah");

        jumlahItemField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        hargaDibayarLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        hargaDibayarLabel.setForeground(new java.awt.Color(0, 0, 0));
        hargaDibayarLabel.setText("Harga Dibayar");

        hargaDibayarField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        catatanLabel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        catatanLabel.setForeground(new java.awt.Color(0, 0, 0));
        catatanLabel.setText("Catatan");

        catatanField.setColumns(20);
        catatanField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        catatanField.setRows(5);
        jScrollPane2.setViewportView(catatanField);

        listBtn.setBackground(new java.awt.Color(108, 117, 125));
        listBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        listBtn.setForeground(new java.awt.Color(255, 255, 255));
        listBtn.setText("Lihat Detail");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(13, 110, 253));
        addBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah Item");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(25, 135, 84));
        saveBtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(keluhanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mekanikLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pelangganLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nopolLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn))
                            .addComponent(mekanikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(pelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(394, 394, 394))
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(separator)
                        .addContainerGap())
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaBarangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahItemField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(catatanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))))))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nopolLabel)
                    .addComponent(nopolField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelangganLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mekanikComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mekanikLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluhanLabel))
                .addGap(19, 19, 19)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catatanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaBarangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarangLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahItemField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahItemLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaDibayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaDibayarLabel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchNopol = nopolField.getText();
        if (searchNopol.isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel, "Nomor Polisi Pelanggan Tidak Boleh Kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Response<PelangganResponseDTO> response = pelangganService.getPelangganByNopol(searchNopol);

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        PelangganResponseDTO pelanggan = response.getData();
        pelangganField.setText(pelanggan.getNama());
        populateMekanikComboBox();
        keluhanField.setEnabled(true);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void handleJasaView() {
        namaBarangComboBox.removeAllItems();
        namaBarangComboBox.setEnabled(false);
        jumlahItemField.setText("1");
        jumlahItemField.setEnabled(false);
        hargaDibayarField.setText("");
        hargaDibayarField.setEnabled(true);
    }

    private void populateNamaBarangComboBox() {
        if (barangList != null) {
            namaBarangComboBox.removeAllItems();
            for (BarangResponseDTO barang : barangList) {
                namaBarangComboBox.addItem(new ComboBoxItem(barang.getNamaBarang(), barang.getNamaBarang()));
            }
            return;
        }

        Response<List<BarangResponseDTO>> response = barangService.getAllBarang();

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        barangList = response.getData();
        namaBarangComboBox.removeAllItems();
        for (BarangResponseDTO barang : barangList) {
            namaBarangComboBox.addItem(new ComboBoxItem(barang.getNamaBarang(), barang.getHargaJual()));
        }
    }

    private void handleBarangView() {
        namaBarangComboBox.setEnabled(true);
        populateNamaBarangComboBox();
        jumlahItemField.setEnabled(true);
        jumlahItemField.setText("");
        hargaDibayarField.setEnabled(false);
        hargaDibayarField.setText("");
    }

    private void jenisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisComboBoxActionPerformed
        // TODO add your handling code here:
        String jenis = (String) jenisComboBox.getSelectedItem();

        if (Objects.equals(jenis, "JASA")) {
            handleJasaView();
        } else if (Objects.equals(jenis, "BARANG")) {
            handleBarangView();
        }
    }//GEN-LAST:event_jenisComboBoxActionPerformed

    private void addJasaAction(String jenis) {
        String hargaDibayarText = hargaDibayarField.getText();
        if (hargaDibayarText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel, "Harga Jasa Masih Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double hargaDibayar = Double.parseDouble(hargaDibayarText);
        if (hargaDibayar <= 0) {
            JOptionPane.showMessageDialog(rootPanel, "Harga Jasa Tidak Boleh Kurang dari atau Sama Dengan Nol", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String catatan = catatanField.getText();

        TransaksiDetailRequestDTO dto = new TransaksiDetailRequestDTO(jenis, "Jasa Servis", 1, hargaDibayar, catatan);
        requestDTO.setDetailRequestDTOList(dto);
        JOptionPane.showMessageDialog(rootPanel, "Item Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }

    private void addBarangAction(String jenis) {
        String jumlahItemText = jumlahItemField.getText();
        if (jumlahItemText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel, "Jumlah Item Masih Kosong", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int jumlahItem = Integer.parseInt(jumlahItemText);
        if (jumlahItem <= 0) {
            JOptionPane.showMessageDialog(rootPanel, "Jumlah Item Tidak Boleh Kurang dari atau Sama Dengan Nol", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double hargaBarang = (double) ((ComboBoxItem) Objects.requireNonNull(namaBarangComboBox.getSelectedItem())).getValue();
        double subtotal = hargaBarang * jumlahItem;
        String namaBarang = (Objects.requireNonNull(namaBarangComboBox.getSelectedItem())).toString();
        String catatan = catatanField.getText();

        TransaksiDetailRequestDTO dto = new TransaksiDetailRequestDTO(jenis, namaBarang, jumlahItem, subtotal, catatan);
        requestDTO.setDetailRequestDTOList(dto);
        JOptionPane.showMessageDialog(rootPanel, "Item Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (requestDTO.getNopol() == null) {
            requestDTO.setNopol(nopolField.getText());
        }

        if (requestDTO.getNamaMekanik() == null) {
            ComboBoxItem selectedMekanik = (ComboBoxItem) mekanikComboBox.getSelectedItem();
            if (selectedMekanik != null) {
                requestDTO.setNamaMekanik(selectedMekanik.toString());
            }
        }

        if (requestDTO.getKeluhan() == null) {
            requestDTO.setKeluhan(keluhanField.getText());
        }

        String jenis = (String) jenisComboBox.getSelectedItem();

        if (Objects.equals(jenis, "JASA")) addJasaAction(jenis);
        else addBarangAction(jenis);

        resetAfterAdd();
    }//GEN-LAST:event_addBtnActionPerformed

    private void resetAfterAdd() {
        jenisComboBox.setSelectedItem("JASA");
        namaBarangComboBox.removeAllItems();
        namaBarangComboBox.setEnabled(false);
        jumlahItemField.setText("1");
        jumlahItemField.setEnabled(false);
        hargaDibayarField.setText("");
        catatanField.setText("");
    }

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        new DetailTransaksiDialog(null, true, requestDTO).setVisible(true);
    }//GEN-LAST:event_listBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (requestDTO.getDetailRequestDTOList().isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel, "Daftar Transaksi Masih Kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        requestDTO.setTotalBelanja();
        Response<String> response = transaksiService.createTransaksi(requestDTO);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Sukses", JOptionPane.INFORMATION_MESSAGE);

        resetAfterCreateTransaction();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetAfterCreateTransaction() {
        nopolField.setText("");
        pelangganField.setText("");
        pelangganLabel.setEnabled(false);
        mekanikComboBox.removeAllItems();
        mekanikComboBox.setEnabled(false);
        keluhanField.setText("");
        keluhanField.setEnabled(false);
        resetAfterAdd();
    }

    private void populateMekanikComboBox() {
        mekanikComboBox.setEnabled(true);
        mekanikComboBox.removeAllItems();

        Response<List<MekanikResponseDTO>> response = mekanikService.getMekanikByStatus(1);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(rootPanel, response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<MekanikResponseDTO> mekanik = response.getData();
        for (MekanikResponseDTO m : mekanik) {
            mekanikComboBox.addItem(new ComboBoxItem(m.getNama(), m.getId()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea catatanField;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextField hargaDibayarField;
    private javax.swing.JLabel hargaDibayarLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisComboBox;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField jumlahItemField;
    private javax.swing.JLabel jumlahItemLabel;
    private javax.swing.JTextArea keluhanField;
    private javax.swing.JLabel keluhanLabel;
    private javax.swing.JButton listBtn;
    private javax.swing.JComboBox<ComboBoxItem> mekanikComboBox;
    private javax.swing.JLabel mekanikLabel;
    private javax.swing.JComboBox<ComboBoxItem> namaBarangComboBox;
    private javax.swing.JLabel namaBarangLabel;
    private javax.swing.JTextField nopolField;
    private javax.swing.JLabel nopolLabel;
    private javax.swing.JTextField pelangganField;
    private javax.swing.JLabel pelangganLabel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
